baseline
baseline: spec
  <baseline>
  spec
    for: #'common'
    do: [ 
      spec
        package: 'SandstoneDb';
        package: 'SandstoneDbFileDirectoryStore';
        package: 'SandstoneGOODS';
        package: 'SandstoneDbFileSystemStore';
        package: 'SandstoneDbFuel';
        package: 'SandstoneDbSqueak';
        package: 'SandstoneDbTests';
        package: 'SandstoneGOODSTests';
        yourself ]